name: release

on:
  release:
    types: [published]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: dtc
          target: x86_64-unknown-linux-gnu
          archive: dtc-$tag-x86_64
          token: ${{ secrets.GITHUB_TOKEN }}
